# Generated by Django 5.0.7 on 2024-08-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoperson',
            options={'ordering': ['-published_date'], 'verbose_name': 'персону', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.RemoveField(
            model_name='cryptoperson',
            name='title',
        ),
        migrations.AlterField(
            model_name='cryptoperson',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
    ]
