# Generated by Django 5.0.7 on 2024-08-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cryptoperson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoperson',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='заголовок'),
        ),
    ]
