# Generated by Django 5.0.6 on 2024-08-04 04:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_category_crypto_short_name_crypto_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='price',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
    ]
