# Generated by Django 5.0.7 on 2024-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_remove_crypto_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'категория'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name': 'криптовалюта', 'verbose_name_plural': 'Криптовалюты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cryptos', to='crypto.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='image',
            field=models.ImageField(upload_to='crypto/images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='тикер'),
        ),
    ]
