# Generated by Django 5.0.6 on 2024-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/images//1659682472110977919.jpg', upload_to='news/images/'),
        ),
    ]
