# Generated by Django 5.0.7 on 2024-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comments'),
        ('users', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='users.profile'),
        ),
    ]
