# Generated by Django 5.0.7 on 2024-08-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_message_dialog_message_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='dialogs', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
