# Generated by Django 5.0.7 on 2024-08-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_dialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.dialog'),
        ),
    ]
